server:
  port: 8080

spring:
  application:
    name: Identity-Reconciliation
  datasource:
    url: jdbc:mysql://mysqldb:3306/bitespeed
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect